# ---------------------------------------------------------------------------
# IAM policy - RWD (Read/Write/Delete) access, scoped to the bucket only
# ---------------------------------------------------------------------------
resource "aws_iam_policy" "rwd_access" {
  name        = local.policy_name
  description = "Read/Write/Delete access to ${var.bucket_arn}/*"

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid      = "ListBucket"
        Effect   = "Allow"
        Action   = ["s3:ListBucket"]
        Resource = [var.bucket_arn]
      },
      {
        Sid      = "ReadWriteDeleteObjects"
        Effect   = "Allow"
        Action   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
        Resource = ["${var.bucket_arn}/*"]
      }
    ]
  })

  tags = var.tags
}

# ---------------------------------------------------------------------------
# IAM role - EC2 trust relationship, external access type: Databricks.
# Trust/cross-account statements are generated by the databricks provider's
# own helper data sources rather than a hardcoded role ARN.
# ---------------------------------------------------------------------------
data "databricks_aws_assume_role_policy" "this" {
  external_id = var.databricks_account_id
}

data "databricks_aws_crossaccount_policy" "this" {}

resource "aws_iam_role" "databricks_role" {
  name = local.role_name

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = concat(
      [
        {
          Sid       = "EC2TrustRelationship"
          Effect    = "Allow"
          Principal = { Service = "ec2.amazonaws.com" }
          Action    = "sts:AssumeRole"
        }
      ],
      jsondecode(data.databricks_aws_assume_role_policy.this.json).Statement
    )
  })

  tags = merge(var.tags, {
    DatabricksWorkspace = local.databricks_workspace_name
  })
}

resource "aws_iam_role_policy" "databricks_crossaccount" {
  name   = "${local.role_name}-databricks-crossaccount"
  role   = aws_iam_role.databricks_role.id
  policy = data.databricks_aws_crossaccount_policy.this.json
}

resource "aws_iam_role_policy_attachment" "attach_rwd" {
  role       = aws_iam_role.databricks_role.name
  policy_arn = aws_iam_policy.rwd_access.arn
}

resource "aws_iam_instance_profile" "this" {
  name = "${local.role_name}-instance-profile"
  role = aws_iam_role.databricks_role.name
}

output "role_arn" {
  value = aws_iam_role.databricks_role.arn
}

output "role_name" {
  value = aws_iam_role.databricks_role.name
}
